path_coverage:
  ros__parameters:
    # 全局坐标系，默认map（规划参考坐标系）
    global_frame: "map"
    
    # 每条路径的宽度（实际为半径）
    robot_width: 0.3
    
    # 认为可通过的最大代价值：如果一个单元格的代价值 ≤ 70，算法就认为这个地方是空地，可以规划路径穿过。
    costmap_max_non_lethal: 70
    
    # 是否执行弓字形分解
    boustrophedon_decomposition: true
    
    # 首先绕着单元格行驶
    border_drive: false
    
    # 机器人基座标系
    base_frame: "base_footprint"
    
    # 在每个 min_wp_dist 中放置的航点数：要插入的航点数量 = (路径段总长度 / min_wp_dist) * num_points
    num_points: 1
    
    # 在考虑拆分之前航点之间的最大距离：如果这个距离大于或等于 min_wp_dist 的值，系统就会认为这段路径太长了，需要在这中间插入更多的点来让路径变得更精细。
    min_wp_dist: 0.2