path_coverage:
  ros__parameters:
    global_frame: "map"
    robot_width: 0.171
    costmap_max_non_lethal: 70
    boustrophedon_decomposition: true
    border_drive: false
    base_frame: "base_footprint"
    num_points: 2
    min_wp_dist: 0.2
    polygon_expand: 0.0
    coverage_clearance: 0.0
    expand_max_non_lethal: 0
    drive_max_non_lethal: 0
